import { useAuth } from './AuthContext';
import { useUI } from './UIContext';
import { useData } from './DataContext';
import { AppContextType } from '../types';

export const useAppContext = (): AppContextType => {
  const auth = useAuth();
  const ui = useUI();
  const data = useData();

  return {
    user: auth.user,
    users: data.users,
    courses: data.courses,
    articles: data.articles,
    team: data.users.filter(u => u.showOnTeamPage),
    projects: data.projects,
    communityPosts: data.communityPosts,
    partners: data.partners,
    supporters: data.supporters,
    events: data.events,
    mentorSessions: data.mentorSessions,
    tracks: data.tracks,
    financialStatements: data.financialStatements,
    annualReports: data.annualReports,
    marketingPosts: data.marketingPosts,
    toast: ui.toast,
    courseProgress: data.courseProgress,
    isProfileModalOpen: ui.isProfileModalOpen,
    selectedProfile: ui.selectedProfile,
    isInscriptionModalOpen: ui.isInscriptionModalOpen,
    selectedCourseForInscription: ui.selectedCourseForInscription,
    instructors: data.instructors,
    mentors: data.mentors,
    loading: data.loading,
    setUser: auth.setUser,
    handleLogout: auth.handleLogout,
    openProfileModal: ui.openProfileModal,
    closeProfileModal: ui.closeProfileModal,
    openInscriptionModal: ui.openInscriptionModal,
    closeInscriptionModal: ui.closeInscriptionModal,
    handleEnrollUser: (courseId: string) => data.handleEnrollUser(courseId, auth.user!),
    completeLesson: (lessonId: string) => data.completeLesson(lessonId, auth.user!),
    handleCompleteOnboarding: () => data.handleCompleteOnboarding(auth.user!, auth.setUser),
    handleSaveNote: (lessonId: string, note: string) => data.handleSaveNote(lessonId, note, auth.user!),
    showToast: ui.showToast,
    handleSaveCourse: (c: any) => data.handleSaveCourse(c, ui.showToast),
    handleDeleteCourse: (cid: string) => data.handleDeleteCourse(cid, ui.showToast),
    handleSaveArticle: (a: any) => data.handleSaveArticle(a, ui.showToast),
    handleDeleteArticle: (aid: string) => data.handleDeleteArticle(aid, ui.showToast),
    handleToggleArticleStatus: (aid: string) => data.handleToggleArticleStatus(aid, ui.showToast),
    handleAddArticleClap: (aid: string) => data.handleAddArticleClap(aid),
    handleSaveUser: (u: any) => data.handleSaveUser(u, auth.user, ui.showToast, auth.setUser),
    handleUpdateUserProfile: (u: any) => data.handleUpdateUserProfile(u, auth.user, ui.showToast, auth.setUser),
    handleDeleteUser: (uid: string) => data.handleDeleteUser(uid, ui.showToast),
    handleSaveProject: (p: any) => data.handleSaveProject(p, ui.showToast),
    handleApproveProject: (pid: string) => data.handleApproveProject(pid, ui.showToast),
    handleRejectProject: (pid: string) => data.handleRejectProject(pid, ui.showToast),
    handleAddClap: (pid: string) => data.handleAddClap(pid),
    handleAddComment: (pid: string, text: string) => data.handleAddComment(pid, text, auth.user!),
    handleSaveEvent: (e: any) => data.handleSaveEvent(e, ui.showToast),
    handleDeleteEvent: (eid: string) => data.handleDeleteEvent(eid, ui.showToast),
    handleSaveTeamOrder: (t: any) => data.handleSaveTeamOrder(t, ui.showToast),
    handleSaveCommunityPost: (p: any) => data.handleSaveCommunityPost(p, ui.showToast),
    handleDeleteCommunityPost: (pid: string) => data.handleDeleteCommunityPost(pid, ui.showToast),
    handleAddCommunityPostClap: (pid: string) => data.handleAddCommunityPostClap(pid),
    handleAddCommunityReply: (pid: string, text: string) => data.handleAddCommunityReply(pid, text, auth.user!),
    handleAddSessionSlot: (mid: string, date: string, time: string) => data.handleAddSessionSlot(mid, date, time, ui.showToast),
    handleRemoveSessionSlot: (mid: string, date: string, time: string) => data.handleRemoveSessionSlot(mid, date, time, ui.showToast),
    handleBookSession: (sid: string) => data.handleBookSession(sid, auth.user!, ui.showToast),
    handleCancelSession: (sid: string) => data.handleCancelSession(sid, ui.showToast),
    handleCreateTrack: (name: string) => data.handleCreateTrack(name, ui.showToast),
    handleUpdateTrack: (tid: string, old: string, new_: string) => data.handleUpdateTrack(tid, old, new_, ui.showToast),
    handleDeleteTrack: (tid: string) => data.handleDeleteTrack(tid, ui.showToast),
    handleSaveFinancialStatement: (s: any) => data.handleSaveFinancialStatement(s, ui.showToast),
    handleDeleteFinancialStatement: (id: string) => data.handleDeleteFinancialStatement(id, ui.showToast),
    handleSaveAnnualReport: (r: any) => data.handleSaveAnnualReport(r, ui.showToast),
    handleDeleteAnnualReport: (id: string) => data.handleDeleteAnnualReport(id, ui.showToast),
    handleSaveMarketingPost: (p: any) => data.handleSaveMarketingPost(p, ui.showToast),
    handleDeleteMarketingPost: (pid: string) => data.handleDeleteMarketingPost(pid, ui.showToast),
  };
};
